# Window Properties
WIDTH = 600
HEIGHT = 800
# Size of pipe image
PIPE_X = 52
PIPE_Y = 320
# Game Settings
INIT_SPEED = 5
GAIN_SPEED = 0.0000000001
PIPE_MIN = 100
PIPE_MAX = HEIGHT - PIPE_MIN
PIPE_GAP_MIN = HEIGHT / 4
PIPE_GAP_MAX = HEIGHT / 2
PIPE_SPAWN = WIDTH
PIPE_TRASH = -1 * PIPE_X
# Bird Bounds
BIRD_MIN_Y = 50
BIRD_MAX_Y = 705
# Bird Physics
# Remember that y=0 is the top of the screen
GRAVITY = 0.1
JUMP_VELOCITY = -10
MAX_VELOCITY = GRAVITY * 20
MIN_VELOCITY = GRAVITY * -50